(function(){let e=document.createElement(`link`).relList;if(e&&e.supports&&e.supports(`modulepreload`))return;for(let e of document.querySelectorAll(`link[rel="modulepreload"]`))n(e);new MutationObserver(e=>{for(let t of e)if(t.type===`childList`)for(let e of t.addedNodes)e.tagName===`LINK`&&e.rel===`modulepreload`&&n(e)}).observe(document,{childList:!0,subtree:!0});function t(e){let t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin===`use-credentials`?t.credentials=`include`:e.crossOrigin===`anonymous`?t.credentials=`omit`:t.credentials=`same-origin`,t}function n(e){if(e.ep)return;e.ep=!0;let n=t(e);fetch(e.href,n)}})();var e=`/assets/book-icon.svg`,t=`/assets/favorites-icon.svg`,n=`/assets/search-icon.svg`,r=`/assets/gray-heart-icon.svg`,i=`/assets/light-theme-icon.svg`,a=`/assets/dark-theme-icon.svg`,o=`/assets/favorites-dark-theme-icon.svg`,s=`/assets/gray-heart-dark-theme-icon.svg`,c=`/assets/red-heart-dark-theme-icon.svg`,l=`/assets/red-heart-icon.svg`,u=`https://openlibrary.org`,d=`https://covers.openlibrary.org/b/id`;async function f(e){let t=encodeURIComponent(e.trim()),n=await fetch(`${u}/search.json?q=${t}&limit=20`);if(!n.ok)throw Error(`Network error`);return(await n.json()).docs.map(e=>({key:e.key,title:e.title||`Unknown title`,authors:e.author_name||[],year:e.first_publish_year||null,coverId:e.cover_i||null}))}function p(e){return e?`${d}/${e}-M.jpg`:null}var m=`library_favorites`;function h(){try{return JSON.parse(localStorage.getItem(m))||[]}catch{return[]}}function g(e){localStorage.setItem(m,JSON.stringify(e))}function _(e){return h().some(t=>t.key===e)}function v(e){let t=h();_(e.key)||g([...t,e])}function y(e){g(h().filter(t=>t.key!==e))}function b(e,t){let n=document.createElement(`div`);n.className=`book-card`,n.dataset.key=e.key;let i=p(e.coverId),a=e.authors.length>0?e.authors.join(`, `):`Unknown author`,o=_(e.key),u=document.documentElement.getAttribute(`data-theme`),d=u===`dark`?s:r,f=u===`dark`?c:l;n.innerHTML=`
    ${i?`<img class="book-card__cover" src="${i}" alt="${e.title}" loading="lazy" />`:`<div class="book-card__cover-placeholder">No cover</div>`}
    <div class="book-card__info">
      <div class="book-card__title" title="${e.title}">${e.title}</div>
      <div class="book-card__author" title="${a}">${a}</div>
      ${e.year?`<div class="book-card__year">${e.year}</div>`:``}
    </div>
    <button class="book-card__fav-btn ${o?`active`:``}" 
            aria-label="${o?`Remove from favorites`:`Add to favorites`}">
      <img src="${o?f:d}" alt="" width="30" height="30" />
    </button>
  `;let m=n.querySelector(`.book-card__fav-btn`),h=m.querySelector(`img`);return m.addEventListener(`click`,()=>{let n=document.documentElement.getAttribute(`data-theme`),i=n===`dark`?s:r,a=n===`dark`?c:l;_(e.key)?(y(e.key),m.classList.remove(`active`),h.src=i,m.setAttribute(`aria-label`,`Add to favorites`)):(v(e),m.classList.add(`active`),h.src=a,m.setAttribute(`aria-label`,`Remove from favorites`)),t()}),n}var x=`/assets/red-heart-list-icon.svg`;function S(e){let t=document.getElementById(`favorites-list`),n=document.getElementById(`favorites-count`),r=h();if(n.textContent=`${r.length} book${r.length===1?``:`s`} saved`,t.innerHTML=``,r.length===0){t.innerHTML=`
      <div class="favorites-empty">
        <p>No favorites yet.</p>
        <p>Click ♡ on any book to save it.</p>
      </div>
    `;return}r.forEach(n=>{let r=p(n.coverId),i=n.authors.length>0?n.authors.join(`, `):`Unknown author`,a=document.createElement(`div`);a.className=`fav-item`,a.innerHTML=`
      ${r?`<img class="fav-item__cover" src="${r}" alt="${n.title}" loading="lazy" />`:`<div class="fav-item__cover"></div>`}
      <div class="fav-item__info">
        <div class="fav-item__title" title="${n.title}">${n.title}</div>
        <div class="fav-item__author">${i}</div>
        ${n.year?`<div class="fav-item__year">${n.year}</div>`:``}
      </div>
      <button class="fav-item__remove" aria-label="Remove from favorites">
        <img src="${x}" alt="" width="16" height="16" />
      </button>
    `,a.querySelector(`.fav-item__remove`).addEventListener(`click`,()=>{y(n.key),S(e),e(n.key)}),t.appendChild(a)})}var C=document.getElementById(`status-message`);function w(e,t=!1){C.textContent=e,C.className=`status-message${t?` error`:``}`}function T(){C.className=`status-message hidden`}function E(e,t){let n=null;return function(...r){clearTimeout(n),n=setTimeout(()=>{e(...r)},t)}}var D=`library_theme`;function O(){return localStorage.getItem(D)||`light`}function k(e){document.documentElement.setAttribute(`data-theme`,e)}function A(e){localStorage.setItem(D,e)}document.querySelector(`.header__logo img`).src=e,document.getElementById(`search-icon`).src=n,document.querySelector(`.favorites-panel__title img`).src=t;var j=document.getElementById(`search-input`),M=document.getElementById(`search-btn`),N=document.getElementById(`books-grid`),P=document.getElementById(`author-filter`),F=document.getElementById(`theme-toggle`),I=[];function L(e){if(N.innerHTML=``,e.length===0){w(`Nothing found. Try a different query.`);return}T(),e.forEach(e=>{let t=b(e,()=>{S(R)});N.appendChild(t)})}function R(e){if(!e)return;let t=N.querySelectorAll(`.book-card`),n=document.documentElement.getAttribute(`data-theme`)===`dark`?s:r;t.forEach(t=>{let r=t.querySelector(`.book-card__fav-btn`);r&&t.dataset.key===e&&(r.classList.remove(`active`),r.querySelector(`img`).src=n,r.setAttribute(`aria-label`,`Add to favorites`))})}async function z(){let e=j.value.trim();if(!e){w(`Please enter a search query.`);return}N.innerHTML=``,w(`Loading...`),M.disabled=!0,P.value=``;try{I=await f(e),L(I)}catch{w(`Network error. Please try again.`,!0)}finally{M.disabled=!1}}function B(){let e=P.value.trim().toLowerCase();if(!e){L(I);return}let t=I.filter(t=>t.authors.some(t=>t.toLowerCase().includes(e)));L(t),t.length===0&&w(`No books found by author "${P.value.trim()}".`)}function V(e){let n=document.getElementById(`theme-icon`);n.src=e===`dark`?i:a,F.setAttribute(`aria-label`,e===`dark`?`Switch to light mode`:`Switch to dark mode`);let r=document.querySelector(`.favorites-panel__title img`);r.src=e===`dark`?o:t}function H(e){let t=e===`dark`?s:r,n=e===`dark`?c:l;N.querySelectorAll(`.book-card`).forEach(e=>{let r=e.querySelector(`.book-card__fav-btn`);r&&(r.classList.contains(`active`)?r.querySelector(`img`).src=n:r.querySelector(`img`).src=t)})}M.addEventListener(`click`,z);var U=E(B,200);P.addEventListener(`input`,U),j.addEventListener(`keydown`,e=>{e.key===`Enter`&&z()});var W=E(z,300);j.addEventListener(`input`,W),F.addEventListener(`click`,()=>{let e=document.documentElement.getAttribute(`data-theme`)===`dark`?`light`:`dark`;k(e),A(e),V(e),H(e)});var G=[`adventure`,`mystery`,`science`,`history`,`fantasy`,`classic`];async function K(){let e=G[Math.floor(Math.random()*G.length)];w(`Loading...`);try{I=await f(e),L(I),j.placeholder=`Try "${e}" or search your own...`}catch{T()}}var q=O();k(q),V(q),S(R),K();